
name: Scala Assignment CI

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - main
      - task_resolution
  pull_request:
    branches:
      - master
      - main
      - task_resolution

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
        with:
          fail_ci_if_error: true